### ISSUE TITLE
Timeout semantic is different from the ruby version

### ISSUE THREAD

**Issue by vheon** [starcraftman/vim-plug#5]
If I'm not mistaken looking at the code you timeout a thread job, so if that job is not completed in said time then we abort the job. The ruby version instead abort the job if it not produce any output for more that said time. You can look at the PlugStream module [plug.vim#L953-L968](https://github.com/junegunn/vim-plug/blob/master/plug.vim#L953-L968) and its use [plug.vim#L1057](https://github.com/junegunn/vim-plug/blob/master/plug.vim#L1057)

**Comment by starcraftman** [comment]
Hi @vheon. I am aware of this difference. I guess I could poll the Popen communicate() to check if any new stdout is written. Will investigate, I guess I'm just used to waiting for procs to finish.

Edit: To be clear, I'll probably get to this after I've proven it can work with Mac & Win since this is more style rather than serious issue.

**Comment by starcraftman** [comment]
As pointed out by vheon, without change to monitoring buffer output for timeout plugins like YCM that take a long time to install fail. Working on this next.

**Comment by starcraftman** [comment]
Nonblocking IO in python a pain and don't think there is an easy equivalent to Timeout::timeout. Python 3 appears to have added something but not available to me in 2.

Question was raised here, they suggested the thread route. Bit of a hassle to make one just to monitor command for output then can use Queue to read lines with nowait and kill after x timeout without lines. Hassle.

Up side is easy to read from queue and update buffer. Annoyance is rest.
